#!/bin/sh

. ./port.sh

port_init "$1" || exit 1

# make the directories where to install
PACKAGE="$(realpath -m "packages/$NAME")"
rm -fr "$PACKAGE"
mkdir -p "$PACKAGE/$PREFIX"

# set DESTDIR
export DESTDIR="$PACKAGE"

port_install

# generate info.ini
cd "$PACKAGE"
echo "# generated by ./package.sh" > info.ini
echo "# see https://github.com/tayoky/ports" >> info.ini
echo "[package]" >> info.ini
echo "name=$1" >> info.ini
echo "host=$HOST" >> info.ini
echo "[dependencies]" >> info.ini

#make the tar
tar -c * -f ../$NAME.tar
