#!/bin/sh

. ./config.mk

SRC=$(realpath ./ports/$1)

. $SRC/$1.ini

#make the directory where to install
rm -fr ./packages/$1
mkdir -p ./packages/$1/bin
mkdir -p ./packages/$1/lib

#set PREFIX
export PREFIX=$(realpath ./packages/$1)
if [ "$git" != "" ] ; then
	cd git/$1
elif [ "$tar" != "" ] ; then
	cd tar/$1
else
	echo "error : no git or tar specified"
	exit
fi

($configure)

cd ../..

./install.sh $1

cd $PREFIX

#info.ini
echo "#generated by ./package.sh" > info.ini
echo "#see https://github.com/tayoky/ports" >> info.ini
echo "[package]" >> info.ini
echo "name=$1" >> info.ini
echo "host=$HOST" >> info.ini
echo "[dependencies]" >> info.ini


#make the tar
tar -c * -f ../$1.tar
